---
title: "NiN analysis Innlandet"
format: html
author: Øystein Sporild Myran
editor: visual 
---

GIS PORTFOLIO PROJECT:

NiN-nature types within simulated 10km x 10km planning area

Innlandet, Norway

## 1. Setup

```{r}

# Load packages
library(sf)
library(dplyr)
library(ggplot2)
library(ggspatial)
```

## 2. Load data

```{r}
# Make path to data
gdb_path <- "~/GIS_data/NiN_data/naturtyper_innlandet.gdb"

# Read nature type data
natur <- st_read(
  gdb_path,
  layer = "naturtyper_nin_omr"
)
```

## 3. Inspect data

```{r}
# Retrieve coordinate reference system
st_crs(natur)
# Return bounding of the data
st_bbox(natur)
# Get names in the data
names(natur)
```

## 4. Find center of data set

```{r}
sentrum <- st_centroid(st_union(natur))
coords <- st_coordinates(sentrum)

x_mid <- coords[1]
y_mid <- coords[2]
```

## 5. Create planning area

```{r}
# Create a simulated 10km x 10km planning area
plan_coords <- matrix(
  c(
    x_mid - 5000, y_mid - 5000,
    x_mid + 5000, y_mid - 5000,
    x_mid + 5000, y_mid + 5000,
    x_mid - 5000, y_mid + 5000,
    x_mid - 5000, y_mid - 5000
  ),
  ncol = 2,
  byrow = TRUE
)

plan_polygon <- st_polygon(list(plan_coords))

plan_sf <- st_sf(
  geometry = st_sfc(
    plan_polygon,
    crs = st_crs(natur)
  )
)
```

## 6. Spatial intersection

```{r}
natur_klippet <- st_intersection(natur, plan_sf)
```

## 7. Area calculations

```{r}
natur_klippet$Areal_ha <-
  as.numeric(st_area(natur_klippet)) / 10000
```

## 8. Summaries

```{r}
#| warning: false
natur_tabell <- st_drop_geometry(natur_klippet)

areal_per_type <- natur_tabell %>%
  group_by(naturtype) %>%
  summarise(
    Areal_ha = sum(Areal_ha, na.rm = TRUE)
  ) %>%
  arrange(desc(Areal_ha))

print(areal_per_type)
```

## 9. Choosing largest nature types for visualization

```{r}
top_types <- areal_per_type %>%
  slice_max(Areal_ha, n = 5) %>%
  pull(naturtype)

natur_klippet$naturgruppe <- ifelse(
  natur_klippet$naturtype %in% top_types,
  natur_klippet$naturtype,
  "Andre naturtyper"
)
```

## 10. Visualization

```{r}
# Bounding box around data
bbox <- st_bbox(natur_klippet)

# Plot map
p_natur_klippet <- ggplot() +

  # Nature types
  geom_sf(
    data = natur_klippet,
    aes(fill = naturgruppe),
    color = "grey30",
    linewidth = 0.1,
    alpha = 0.9
  ) +

  # Zoom to data
  coord_sf(
    xlim = c(bbox$xmin - 500, bbox$xmax + 500),
    ylim = c(bbox$ymin - 500, bbox$ymax + 500),
    expand = FALSE
  ) +
  
  # Natural color palette 
  scale_fill_brewer(
    palette = "PuOr",
    name = "Naturtype"
  ) +

  # North arrow
  annotation_north_arrow(
    location = "tr",
    which_north = "true",
    style = north_arrow_orienteering(),
    height = unit(0.8, "cm"),
    width = unit(0.8, "cm"),
    pad_x = unit(0.5, "cm")
  ) +

  # Scale
  annotation_scale(
    location = "bl",
    width_hint = 0.3
  ) +

  # Minimalistic theme
  theme_minimal(base_size = 12) +

  labs(
    title = "Kartlagte NiN-naturtyper",
    subtitle = "Simulert analyseomraade i Innlandet",
    fill = "Naturtype"
  ) +

  theme(
    panel.grid = element_blank(),
    axis.title = element_blank(),
    plot.title = element_text(
      face = "bold",
      size = 16
    ),
    legend.position = "right"
  )

# Print plot
p_natur_klippet

```

## 11. Export figure

```{r}
# Save map as PNG in figures-folder
ggsave(
  filename = "figures/portfolio_map_clean.png",
  plot = p_natur_klippet,
  width = 10,
  height = 7,
  dpi = 300
)
```
